title: "Dhruv Gamdha"
description: "HPC Software Developer Specializing in GPU Acceleration and PDE Solvers"
url: "https://DhruvGamdha.github.io" # Replace with your GitHub Pages URL
baseurl: "" # For user.github.io repositories, leave empty
# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"

# header not working
# header:
#   # overlay_image: "/assets/images/header.jpg"
#   overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
#   caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
  # navigation:
  #   - label: "About"
  #     url: "/about/"
  #   - label: "Projects"
  #     url: "/projects/"
  #   - label: "Publications"
  #     url: "/publications/"
  #   - label: "Resume"
  #     url: "/resume/"
  #   - label: "Contact"
  #     url: "/contact/"

# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       author_profile: true
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       author_profile: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme  # Make sure this is included!
  - jekyll-include-cache

# Minimal Mistakes specific configurations
author:
  name: "Dhruv Gamdha"
  avatar: "/assets/images/avatar.jpg" # Ensure this image exists
  bio: "Ph.D. Candidate in HPC and Simulation"
  links:
    - label: "Email"
      url: "mailto:dgamdha@iastate.edu"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/dhruv-dhiraj-gamdha/"
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=P2KcbCAAAAAJ&hl=en"

# Navigation links in the header
navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Resume"
    url: /resume/
  - title: "Contact"
    url: /contact/

# Enable extra features
extras:
  - favicon
  - apple-touch-icon

# Social links can also be defined here
social:
  - icon: linkedin
    link: https://www.linkedin.com/in/dhruv-dhiraj-gamdha/
  - icon: email
    link: mailto:dgamdha@iastate.edu
  - icon: scholar
    link: https://scholar.google.com/citations?user=P2KcbCAAAAAJ&hl=en

# Optional: Customize the footer
footer:
  copyright:
    text: "© 2024 Dhruv Gamdha. All rights reserved."